# Generated by Django 4.1.3 on 2022-12-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1000)),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='contactinfo',
        ),
    ]
