# Generated by Django 4.1.3 on 2022-12-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_contactinfo_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=1000)),
                ('staff', models.CharField(max_length=150)),
                ('date', models.DateTimeField(verbose_name='')),
                ('reason', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=1000)),
                ('petname', models.CharField(max_length=150)),
                ('lastvisit', models.DateTimeField(verbose_name='')),
                ('staff', models.CharField(max_length=150)),
            ],
        ),
    ]
