# Generated by Django 4.2 on 2023-04-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs410', '0004_main_makes_models_ratings_states'),
    ]

    operations = [
        migrations.DeleteModel(
            name='defaultDB',
        ),
        migrations.DeleteModel(
            name='usersDB',
        ),
    ]
